version: '3'

services:
  app:
    image: jupyter/pyspark-notebook:lab-3.1.13
    ports:
    - 8888:8888
    volumes:
    - "./docker_local/:/home/jovyan/work"
    environment:
    - JUPYTER_ENABLE_LAB=yes